export const pathNames = {
  root: '/',
  wildcard: '*',
  login: '/login',
  homepage: '/',
  orders: '/orders',
  products: '/products',
  categories: '/categories',
  subCategories: '/subCategories',
  analytics: '/analytics',
  payments: '/payments',
  announcements: '/announcements',
  support: '/support',
  priceRecommendations: '/priceRecommendations',
  qualityDashboard: '/qualityDashboard',
  notices: '/notices',
  settings: '/settings',
  logout: '/logout',
  addProduct:'/products/addproduct',
  editCategory :'/categories/editcategory',
  editProduct:'/products/editproduct',
};

export const rootPathNames = {
  root: '/',
  wildcard: '*',
  homepage: '/*',
  login: '/login/*',
  orders: '/orders/*',
  products: '/products/*',
  categories: '/categories/*',
  subCategories: '/subCategories/*',
  analytics: '/analytics/*',
  payments: '/payments/*',
  announcements: '/announcements/*',
  support: '/support/*',
  priceRecommendations: '/priceRecommendations/*',
  qualityDashboard: '/qualityDashboard/*',
  notices: '/notices/*',
  settings: '/settings/*',
  logout: '/logout/*',
  addProduct:'/products/addproduct/*',
  viewProduct:'/prducts/viewproduct/*',
  editCategory: '/categories/editcategory/*',
  editProduct:'/products/editproduct/*',
};

