export const pathNames = {
  root: '/',
  wildcard: '*',
  login: '/login',
  homepage: '/home/',
  orders: '/orders',
  products: '/products',
  analytics: '/analytics',
  payments: '/payments',
  announcements: '/announcements',
  support: 'https://uoons.com',
  priceRecommendations: '/priceRecommendations',
  qualityDashboard: '/qualityDashboard',
  notices: '/notices',
  settings: '/settings',
  logout: '/logout',
};

export const rootPathNames = {
  root: '/',
  wildcard: '*',
  homepage: '/home/*',
  login: '/login/*',
  orders: '/orders/*',
  products: '/products/*',
  analytics: '/analytics/*',
  payments: '/payments/*',
  announcements: '/announcements/*',
  support: 'https://uoons.com/*',
  priceRecommendations: '/priceRecommendations/*',
  qualityDashboard: '/qualityDashboard/*',
  notices: '/notices/*',
  settings: '/settings/*',
  logout: '/logout/*',
};
