export const pathNames = {
  root: '/',
  wildcard: '*',
  login: '/login',
  homepage: '/',
  orders: '/orders',
  products: '/products',
  categories: '/categories',
  analytics: '/analytics',
  payments: '/payments',
  announcements: '/announcements',
  support: 'https://uoons.com',
  priceRecommendations: '/priceRecommendations',
  qualityDashboard: '/qualityDashboard',
  notices: '/notices',
  settings: '/settings',
  logout: '/logout',
  addProduct:'/products/addproduct'
};

export const rootPathNames = {
  root: '/',
  wildcard: '*',
  homepage: '/*',
  login: '/login/*',
  orders: '/orders/*',
  products: '/products/*',
  categories: '/categories/*',
  analytics: '/analytics/*',
  payments: '/payments/*',
  announcements: '/announcements/*',
  support: 'https://uoons.com/*',
  priceRecommendations: '/priceRecommendations/*',
  qualityDashboard: '/qualityDashboard/*',
  notices: '/notices/*',
  settings: '/settings/*',
  logout: '/logout/*',
  addProduct:'/products/addproduct/*',
  viewProduct:'/prducts/viewproduct/*'
};
